### ISSUE TITLE
remove redundant page tags on custompage1.php

### ISSUE THREAD

**Issue by greglinch** [lexinal/final-project-#25]
The WordPress theme already has all of these tags (html, head, body), so they're unnecessary and can only serve to possible confuse a browser:

https://github.com/lexinal/final-project-/blob/master/themes/twentyseventeen-child/custompage1.php#L24-L25

https://github.com/lexinal/final-project-/blob/master/themes/twentyseventeen-child/custompage1.php#L33-L34

https://github.com/lexinal/final-project-/blob/master/themes/twentyseventeen-child/custompage1.php#L174

https://github.com/lexinal/final-project-/blob/master/themes/twentyseventeen-child/custompage1.php#L180

**Comment by lexinal** [comment]
Fixed!
