### ISSUE TITLE
Double-Check that this is Mobile Friendly

### ISSUE THREAD

**Issue by sidlowsh** [lexinal/final-project-#3]
I just tested roadtofit.xyz on mobile and I couldn't get the various menu items to load. Double check the skeleton of your site to make sure those pages still work. Here's a Stack Exchange link that might help: https://wordpress.stackexchange.com/questions/221593/wordpress-website-loads-fine-on-desktop-browsers-but-safari-for-ios-cannot-load

**Comment by lexinal** [comment]
Thank you! looks like it is working now
