### ISSUE TITLE
Cup Image

### ISSUE THREAD

**Issue by Faherelfayez** [lexinal/final-project-#6]
You said you had an issue with the cup image. Did you try accessing your site on private mode? Maybe that is why the photo keeps showing up because of you caches

**Comment by cordawso** [comment]
I also noticed this — If you don't want it, you could just get rid of it altogether by either deleting the image from your media file or using CSS to call the ID or class in your child theme and display nothing.

**Comment by szs10** [comment]
Fitness definitely gives you a decent adrenaline kick, however I would consider changing this image, in order to make your website more consistent. A good resource online for free, high quality photos is [Unsplash](https://unsplash.com) - you should check it out!

**Comment by lexinal** [comment]
Thank you both for the feedback!
